// This file was generated by py/makeversionhdr.py
#define MICROPY_GIT_TAG "2.2.4-2-gcfcbb36"
#define MICROPY_GIT_HASH "cfcbb36"
#define MICROPY_BUILD_DATE "2018-04-10"
#define MICROPY_VERSION_MAJOR (2)
#define MICROPY_VERSION_MINOR (2)
#define MICROPY_VERSION_MICRO (4)
#define MICROPY_VERSION_STRING "2.2.4"
#define MICROPY_FULL_VERSION_INFO ("Adafruit CircuitPython " MICROPY_GIT_TAG " on " MICROPY_BUILD_DATE "; " MICROPY_HW_BOARD_NAME " with " MICROPY_HW_MCU_NAME)
